services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432'
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - 'SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'