TRUNCATE TABLE ingredient CASCADE;

INSERT INTO ingredient (id, name) VALUES
-- essentials
(nextval('ingredient_id_seq'), 'salt'),
(nextval('ingredient_id_seq'), 'black pepper'),
(nextval('ingredient_id_seq'), 'olive oil'),
(nextval('ingredient_id_seq'), 'vegetable oil'),
(nextval('ingredient_id_seq'), 'sugar'),

-- fruits and vegetables
(nextval('ingredient_id_seq'), 'yellow onion'),
(nextval('ingredient_id_seq'), 'red onion'),
(nextval('ingredient_id_seq'), 'bean sprouts'),
(nextval('ingredient_id_seq'), 'red pepper'),
(nextval('ingredient_id_seq'), 'garlic clove'),
(nextval('ingredient_id_seq'), 'spring onion'),
(nextval('ingredient_id_seq'), 'carrot'),
(nextval('ingredient_id_seq'), 'chopped tomatoes'),
(nextval('ingredient_id_seq'), 'lettuce'),
(nextval('ingredient_id_seq'), 'jalapeño'),
(nextval('ingredient_id_seq'), 'red chilli'),
(nextval('ingredient_id_seq'), 'ginger'),
(nextval('ingredient_id_seq'), 'celery'),
(nextval('ingredient_id_seq'), 'radish'),
(nextval('ingredient_id_seq'), 'sweetcorn'),
(nextval('ingredient_id_seq'), 'spinach'),
(nextval('ingredient_id_seq'), 'green peas'),
(nextval('ingredient_id_seq'), 'cucumber'),
(nextval('ingredient_id_seq'), 'broccoli'),
(nextval('ingredient_id_seq'), 'leek'),
(nextval('ingredient_id_seq'), 'red cabbage'),
(nextval('ingredient_id_seq'), 'tomato'),
(nextval('ingredient_id_seq'), 'avocado'),
(nextval('ingredient_id_seq'), 'pitted olives'),
(nextval('ingredient_id_seq'), 'potato'),
(nextval('ingredient_id_seq'), 'sweet potato'),
(nextval('ingredient_id_seq'), 'lemon'),
(nextval('ingredient_id_seq'), 'lime'),

-- proteins, lentils, beans
(nextval('ingredient_id_seq'), 'chicken breast'),
(nextval('ingredient_id_seq'), 'chicken thigh'),
(nextval('ingredient_id_seq'), 'sausage'),
(nextval('ingredient_id_seq'), 'beef mince'),
(nextval('ingredient_id_seq'), 'turkey mince'),
(nextval('ingredient_id_seq'), 'egg'),
(nextval('ingredient_id_seq'), 'tofu'),
(nextval('ingredient_id_seq'), 'dried red lentils'),
(nextval('ingredient_id_seq'), 'canellini beans'),
(nextval('ingredient_id_seq'), 'salmon'),

-- carbs
(nextval('ingredient_id_seq'), 'rice noodles'),
(nextval('ingredient_id_seq'), 'long-grain rice'),
(nextval('ingredient_id_seq'), 'short-grain rice'),
(nextval('ingredient_id_seq'), 'jasmine rice'),
(nextval('ingredient_id_seq'), 'pasta'),

-- sauce ingredients
(nextval('ingredient_id_seq'), 'fish sauce'),
(nextval('ingredient_id_seq'), 'soy sauce'),
(nextval('ingredient_id_seq'), 'honey'),
(nextval('ingredient_id_seq'), 'rice vinegar'),
(nextval('ingredient_id_seq'), 'sriracha'),
(nextval('ingredient_id_seq'), 'peanut butter'),
(nextval('ingredient_id_seq'), 'tomato paste'),
(nextval('ingredient_id_seq'), 'natural yogurt'),
(nextval('ingredient_id_seq'), 'coconut milk'),
(nextval('ingredient_id_seq'), 'chili oil'),
(nextval('ingredient_id_seq'), 'mayonnaise'),
(nextval('ingredient_id_seq'), 'chicken stock'),
(nextval('ingredient_id_seq'), 'vegetable stock'),
(nextval('ingredient_id_seq'), 'harissa paste'),
(nextval('ingredient_id_seq'), 'tomato pesto'),
(nextval('ingredient_id_seq'), 'green pesto'),
(nextval('ingredient_id_seq'), 'red wine vinegar'),
(nextval('ingredient_id_seq'), 'balsamic vinegar'),
(nextval('ingredient_id_seq'), 'thai green curry paste'),
(nextval('ingredient_id_seq'), 'thai red curry paste'),

-- fresh herbs
(nextval('ingredient_id_seq'), 'parsley'),
(nextval('ingredient_id_seq'), 'coriander'),
(nextval('ingredient_id_seq'), 'basil'),
(nextval('ingredient_id_seq'), 'thyme'),
(nextval('ingredient_id_seq'), 'dill'),
(nextval('ingredient_id_seq'), 'bay leaf'),

-- dried herbs and spices
(nextval('ingredient_id_seq'), 'mixed herbs'),
(nextval('ingredient_id_seq'), 'ground cumin'),
(nextval('ingredient_id_seq'), 'smoked paprika'),
(nextval('ingredient_id_seq'), 'red pepper flakes'),
(nextval('ingredient_id_seq'), 'garam masala'),
(nextval('ingredient_id_seq'), 'ground coriander'),
(nextval('ingredient_id_seq'), 'ground turmeric'),
(nextval('ingredient_id_seq'), 'ground cinnamon'),
(nextval('ingredient_id_seq'), 'ground nutmeg'),
(nextval('ingredient_id_seq'), 'ground cloves'),
(nextval('ingredient_id_seq'), 'ground ginger'),
(nextval('ingredient_id_seq'), 'cayenne pepper'),
(nextval('ingredient_id_seq'), 'sesame seeds'),
(nextval('ingredient_id_seq'), 'chilli powder'),
(nextval('ingredient_id_seq'), 'onion powder'),
(nextval('ingredient_id_seq'), 'garlic powder'),
(nextval('ingredient_id_seq'), 'dried oregano'),
(nextval('ingredient_id_seq'), 'dried dill'),
(nextval('ingredient_id_seq'), 'dried thyme'),
(nextval('ingredient_id_seq'), 'dried parsley'),
(nextval('ingredient_id_seq'), 'dried basil'),
(nextval('ingredient_id_seq'), 'dried rosemary'),

-- dairy
(nextval('ingredient_id_seq'), 'butter'),
(nextval('ingredient_id_seq'), 'feta'),
(nextval('ingredient_id_seq'), 'cheddar cheese'),
(nextval('ingredient_id_seq'), 'parmesan'),
(nextval('ingredient_id_seq'), 'mozzarella cheese'),
(nextval('ingredient_id_seq'), 'goat''s cheese'),

-- nuts
(nextval('ingredient_id_seq'), 'cashews'),
(nextval('ingredient_id_seq'), 'pine nuts'),
(nextval('ingredient_id_seq'), 'peanuts');