spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  datasource:
    data: classpath:/sample-data/ingredients.sql
  banner:
    location: classpath:/static/banner-dev.txt